### PR TITLE
Fix some warnings from maven.

### PR DESCRIPTION
**Pull request by rakhmad**
I am running this workshop, and there were some warning from executing maven, so I add fixes for those warnings.

### CODE REVIEW

**Comment by danieloh30** [comment]
@rakhmad what warning messages do you see in CRW? what is your issue when you use a 1.6.0 version? The spring session project is based on a DG quickstart(https://github.com/redhat-developer/redhat-datagrid-tutorials/blob/RHDG_8.1.0/pom.xml) which we're testing it.

**Comment by rakhmad** [comment]
@danieloh30 the warning is telling that there is no version tag for `exec-maven-plugin`. I did not see the DG quickstart before so I searched from mvnrepository.com for the version. If I use 1.6.0 the warning is fixed, I updated it because it use the latest version. But then, I was not aware about the DG quickstart.

**Comment by danieloh30** [comment]
@rakhmad Can you share the warning in your CRW? Because I don't see any warning message in my CRW of this workshop environment. Also, there's no issue to build and deploy the application.

**Comment by rakhmad** [comment]
@danieloh30 here's output from executing `mvn clean compile` in my laptop:
```bash
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.example:dg8-exercises:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 50, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ---------------------< org.example:dg8-exercises >----------------------
[INFO] Building dg8-exercises 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from redhat-ga: https://maven.repository.redhat.com/ga/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml
Downloading from redhat-early-access: https://maven.repository.redhat.com/earlyaccess/all/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml
Downloaded from redhat-early-access: https://maven.repository.redhat.com/earlyaccess/all/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml (431 B at 96 B/s)
Downloaded from redhat-ga: https://maven.repository.redhat.com/ga/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml (395 B at 81 B/s)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dg8-exercises ---
[INFO] Deleting /Users/rakhmad/Documents/Development/Work/dg8-workshop-labs/dg8-exercises/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dg8-exercises ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/rakhmad/Documents/Development/Work/dg8-workshop-labs/dg8-exercises/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dg8-exercises ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 7 source files to /Users/rakhmad/Documents/Development/Work/dg8-workshop-labs/dg8-exercises/target/classes
[WARNING] /Users/rakhmad/Documents/Development/Work/dg8-workshop-labs/dg8-exercises/src/main/java/org/acme/Exercise6.java: /Users/rakhmad/Documents/Development/Work/dg8-workshop-labs/dg8-exercises/src/main/java/org/acme/Exercise6.java uses or overrides a deprecated API.
[WARNING] /Users/rakhmad/Documents/Development/Work/dg8-workshop-labs/dg8-exercises/src/main/java/org/acme/Exercise6.java: Recompile with -Xlint:deprecation for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.837 s
[INFO] Finished at: 2020-10-02T17:06:07+07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by danieloh30** [comment]
@rakhmad Cool. Just confirmed and merged it. Thx for your contribution!!

**Pull request merged**
